name: none-shall-pass

on:
  push:
    branches: [ main ]

jobs:
  none-shall-pass:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - uses: thevickypedia/none-shall-pass@v2.0
